language: rust
sudo: required
rust:
  - nightly
  - beta
  - stable
  - 1.14.0 # rustc on debian stable
cache: cargo

script:
  - cargo test

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: target/kcov/merged
  on:
    branch: master
    rust: stable
  script:
  - mkdir target/kcov target/kcov/unit target/kcov/integration target/kcov/merged
  - kcov target/kcov/unit target/debug/lightning_invoice-!(*.d)
  - kcov target/kcov/integration target/debug/ser_de-!(*.d)
  - kcov target/kcov/unit target/debug/lightning_invoice-!(*.d)

before_install:
  - sudo apt-get update
  - sudo apt-get install cmake g++ pkg-config jq libcurl4-openssl-dev libelf-dev libdw-dev binutils-dev libiberty-dev
  - cargo install cargo-kcov || true
  - cargo kcov --print-install-kcov-sh | sh