language: rust
sudo: required
rust:
  - nightly
  - beta
  - stable
  - 1.14.0 # rustc on debian stable
cache: cargo

jobs:
  include:
  - stage: test
    script: cargo test
  - stage: coverage
    rust: stable
    branches:
      only:
      - master
    script: bash .travis-kcov.sh

before_install:
  - sudo apt-get update
  - sudo apt-get install cmake g++ pkg-config jq libcurl4-openssl-dev libelf-dev libdw-dev binutils-dev libiberty-dev
  - cargo install cargo-kcov || true
  - cargo kcov --print-install-kcov-sh | sh