[package]
name = "lightning-invoice"
version = "0.1.0"
authors = ["Sebastian Geisler <sgeisler@wh2.tu-dresden.de>"]

[dependencies]
bech32 = {git = "https://github.com/sgeisler/rust-bech32"}
regex = "0.2"
chrono = "0.4"
secp256k1 = "0.8"
bitcoin = "0.11"

[dev-dependencies]
hex = "0.3.1"