[package]
name = "lightning-invoice"
version = "0.1.0"
authors = ["Sebastian Geisler <sgeisler@wh2.tu-dresden.de>"]
license = "Apache-2.0"

[dependencies]
bech32 = "0.3.1"
regex = "0.2"
chrono = "0.4"
secp256k1 = "0.8"
bitcoin = "0.11"

[dev-dependencies]
binary_macros = "0.6"